#!/bin/sh

#-Dorg.lwjgl.util.DebugLoader=true -Dorg.lwjgl.util.Debug=true

# Mac command
# exec java -XstartOnFirstThread -jar Ikala-Core-0.6.0.jar

# Windows command
exec java -jar Ikala-Core-0.6.0.jar
